const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const html=fs.readFileSync(path.join(__dirname,'../archive.html'),'utf8');
const dom=new JSDOM(html,{url:'http://localhost/archive.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;
w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=function(){};
for(const s of d.querySelectorAll('script:not([src])'))w.eval(s.textContent);
assert.equal(d.querySelectorAll('.row').length,50);assert.ok(d.getElementById('record'));
for(const a of d.querySelectorAll('a[href^="#"]'))assert.ok(d.getElementById(a.getAttribute('href').slice(1)),a.outerHTML);
const q=d.getElementById('q');q.value='1993';q.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.row').length,1);
q.value=' ';q.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.row').length,50);
for(const b of d.querySelectorAll('.lg'))b.click();assert.equal(d.querySelectorAll('.row').length,0);assert.ok(d.querySelector('.empty'));
d.getElementById('archive-reset').click();assert.equal(d.querySelectorAll('.row').length,50);assert.equal(d.activeElement,q);assert.equal(d.getElementById('archive-reset').hidden,true);
const marks=[...d.querySelectorAll('.mk')];assert.equal(marks.length,50);assert.equal(marks.filter(c=>c.getAttribute('tabindex')==='0').length,1);
marks[0].focus();marks[0].dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(d.activeElement,marks[1]);
marks[1].dispatchEvent(new w.KeyboardEvent('keydown',{key:'End',bubbles:true}));assert.equal(d.activeElement,marks.at(-1));
const entryIndex=marks.at(-1).dataset.i;marks.at(-1).dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal(d.activeElement,d.querySelector('#archive-entry-'+entryIndex+' h4'));
for(const a of d.querySelectorAll('.row a'))assert.ok(a.getAttribute('aria-label').includes('(opens in a new tab)'));
assert.ok(d.getElementById('archive-count').textContent.includes('archived entries'));
console.log('PASS: archive anchors, year search, whitespace, all-series-off recovery, result counts, roving chart keyboard navigation, selected-entry focus, and named source links.');dom.window.close();
