const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const root=path.join(__dirname,'..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://gordonusc.github.io/media-log/?keep=1&year=2020&media=screen&q=Netflix#record',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;w.HTMLElement.prototype.scrollIntoView=function(){};
for(const f of ['media-data.js','site.js'])w.eval(fs.readFileSync(path.join(root,f),'utf8'));
const year=d.querySelector('#record-year'),q=d.querySelector('#search'),items=()=>[...d.querySelectorAll('.record-item')];
assert.equal(year.value,'2020');assert.equal(items().length,1);assert.match(items()[0].textContent,/High Score/);
assert.deepEqual([...year.options].slice(1).map(o=>o.value),[...new Set(w.MEDIA_ENTRIES.map(e=>String(e.year)))].sort((a,b)=>Number(b)-Number(a)));
d.querySelector('#reset-record').click();assert.equal(year.value,'all');assert.equal(new w.URL(w.location.href).searchParams.has('year'),false);assert.equal(new w.URL(w.location.href).searchParams.get('keep'),'1');
year.value='2025';year.dispatchEvent(new w.Event('change'));assert.ok(items().length);assert.ok(items().every(e=>e.querySelector('.year').textContent==='2025'));assert.equal(new w.URL(w.location.href).searchParams.get('year'),'2025');assert.equal(d.querySelector('#reset-record').hidden,false);
q.value='not-present-ever';q.dispatchEvent(new w.Event('input'));assert.ok(d.querySelector('.empty'));d.querySelector('#reset-record').click();assert.equal(items().length,8);assert.equal(year.value,'all');
d.querySelector('#more-records').click();w.history.pushState(null,'','#watch');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(items().length,16);
w.history.pushState(null,'','?year=2020');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(year.value,'2020');assert.ok(items().every(e=>e.querySelector('.year').textContent==='2020'));
w.history.pushState(null,'','?year=invalid');w.dispatchEvent(new w.PopStateEvent('popstate'));assert.equal(year.value,'all');assert.equal(items().length,8);
const play=d.querySelector('#play-video'),stop=d.querySelector('#stop-video'),player=d.querySelector('#video-player');assert.equal(d.querySelectorAll('iframe').length,0);assert.equal(stop.hidden,true);
play.click();assert.equal(player.hidden,false);assert.equal(play.hidden,true);assert.equal(stop.hidden,false);assert.equal(d.querySelectorAll('iframe').length,1);assert.equal(d.activeElement.tagName,'IFRAME');
stop.click();assert.equal(player.hidden,true);assert.equal(player.children.length,0);assert.equal(stop.hidden,true);assert.equal(play.hidden,false);assert.equal(d.activeElement,play);
play.click();assert.equal(d.querySelectorAll('iframe').length,1);stop.click();assert.equal(d.querySelectorAll('iframe').length,0);
dom.window.close();console.log('PASS Media: year choices derived from records, compound bookmarked filters, empty/reset recovery, preserved unrelated parameters and hash-only pagination, invalid-year fallback; opt-in playback, stop unload, focus return, and replay. jsdom only; actual YouTube playback unverified.');
